# file: tasks/build_container.yml

- name: DOCKER | checkout projects from github
  git: repo={{ repo_url }}
       version={{ repo_version }}
       dest={{ tmp_dest }}
       accept_hostkey=yes
  register: docker_downloaded

- name: DOCKER | build the image
  become: yes
  command: docker build -t "built-by-ansible:gocd-agent-pi-erlang" {{ tmp_dest }}
  when: docker_downloaded.changed
