# file: tasks/build_container.yml

- name: DOCKER | checkout projects from github
  git: repo={{ repo_url }}
       version={{ repo_version }}
       dest={{ tmp_dest }}
       accept_hostkey=yes
       key_file={{ rsa_key }}
  register: magma_downloaded

- name: DOCKER | build the image
  command: docker build -t "built-by-ansible:gocd-agent-pi-erlang" {{ tmp_dest }}

- name: DOCKER | run the site in a docker container
  docker:
    name: gocd-agent
    image: "built-by-ansible:gocd-agent-pi-erlang"
    state: reloaded
    publish_all_ports: yes
    use_tls: encrypt
