# tasks/run_container.yml

# requires ansible 2.1.0.0
- name: DOCKER | run the site in a docker container
  become: yes
  docker_container:
    name: gocd-agent
    image: "built-by-ansible:gocd-agent-pi-erlang"
    state: started
    restart: yes
    network_mode: host
  #when: dockerfile.changed
