# tasks/run_container.yml

# - name: DOCKER | run the site in a docker container
#   become: yes
#   #become_user: pi
#   docker: name=gocd-agent
#           image="built-by-ansible:gocd-agent-pi-erlang"
#           state=reloaded
#           publish_all_ports=yes
#           use_tls=encrypt
#   #when: docker_downloaded.changed

# - name: DOCKER | make sure docker is started (and runs on boot)
#   become: yes
#   service: name=docker state=started enabled=yes
  #when: hypriot_image_downloaded.changed

# requires ansible 2.1.0.0
- name: DOCKER | run the site in a docker container
  become: yes
  docker_container:
    name: gocd-agent
    image: "built-by-ansible:gocd-agent-pi-erlang"
    state: started
    restart: yes
    restart_policy: always
    #network_mode: host
  #when: dockerfile.changed

- name: DOCKER | Create gocd-agent service
     template: src=templates/gocd-agent.service-template.j2 dest=/etc/systemd/system/gocd-agent.service

- name: DOCKER | run the container
     service: name=gocd-agent state=started enabled=yes
